### ISSUE TITLE
exception error if we are placing an order with total more than "Maximum Order Total"

### ISSUE THREAD

**Issue by gtrocks** [ratepay/magento2-module#98]
instead of showing the correct error message for the condition we are getting an exception error when we try to place an order with a total of more than "Maximum Order Total".

**Comment by MartinKuhl** [comment]
@markusmichalski-fc could you please check?

**Comment by FatchipRobert** [comment]
Hello @gtrocks ,

what do you mean with "exception error" in this case?
Do you mean one of these classic Magento2 exception pages?
![Ratepay_Issue_98_exceptionbox](https://github.com/ratepay/magento2-module/assets/25302155/cd9d9267-3ae4-4d66-885e-30c08a367b93)

If YES:
Could please check the var/log/ folder of your shop if there is any information concerning this error in the exception.log, debug.log oder system.log file and post it here.

If NO:
I just checked what happens when trying to create an order with a higher total than the maximum order total specified by the used Ratepay profile.

First of all you shouldn't even be able to choose a Ratepay payment method when the current order total is higher than the maximum order total of the used Ratepay profile, because the module should only show Ratepay payment methods that are allowed for the current basket.

I enabled this misbehaviour by changing some info in the database and in this case i got this behaviour when trying to create an order (maximum order total was 300€):
![Ratepay_Issue_98_errorbox](https://github.com/ratepay/magento2-module/assets/25302155/755f3682-07ea-4ad3-8e20-13d2b7a22b40)

Is this the behaviour you got?

**Comment by MartinKuhl** [comment]
closed due to inactivity

**Comment by gtrocks** [comment]
@FatchipRobert 
If you add a company value while placing an order then it will show condition according to the B2B 
And visable to you on backend and frontend both but not allow to place order and create issue .
I have seen commit that resolved this issue for me 
Now https://github.com/ratepay/magento2-module/commit/dbde8aed8da78379c72f8db86295d5d7ec9c106a
